### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by ghost** [bazo-blockchain/bazo-client#10]
Hi Marc,

I'm having trouble building the client:
```
# github.com/bazo-blockchain/bazo-client/network
network/connect.go:53:17: undefined: p2p.PrepareHandshake
network/connect.go:53:38: undefined: p2p.CLIENT_PING
network/connect.go:62:36: undefined: p2p.CLIENT_PONG
network/incoming.go:26:7: undefined: p2p.BLOCK_HEADER_BRDCST
network/requests.go:70:27: undefined: p2p.RcvData_
network/requests.go:88:27: undefined: p2p.RcvData_
```

Which (past) revision of `bazo-miner` is required to build the (latest) client?
Shouldn't there be a call to `p2p.Init()` with the latest `bazo-miner`?

Thanks,
Andreas

**Comment by mchetelat** [comment]
Hi Andreas

Please use the last revision of the branch "aduno". In the next couple of days I will merge it to master branch.

Cheers Marc

**Comment by ghost** [comment]
Thanks, that worked.
